- IT-31/pavlyshynets/README.md
> Lab_1: Created

- IT-31/Hrytsyk/README.md
Грицик Олег Анатолійович. Лабораторна робота №1
> Lab_1: створено

- IK-31/PastukhVova/README.md
> Pastukh V.A. Lab1

- IT-31/Domalchuk/README.md
Домальчук Богдан Васильвич ІТ-31
> Lab_1: + Bohdan Domalchuk

- IT-31/Shynkler/README.md
Шинклер Тарас Андрійович Lab_1
> Lab_1 done!

- IT-31/Domalchuk/README.md
Домальчук Богдан Васильович Лабораторна робота №1
> lab_1: + Domalchuk

- IT-31/Sotnyk/README.md
> Lab_1: Lab1 Сотник Віталій ІТ 31

- IK-31/Bobyk/README.md
Бобик Юрій Володирович. Лабораторна №1
> Lab_1 created

- IT-31/Pavlenko/README.md
створила папку Pavlenko з власним README файлом
Павленко Катерина Костянтинівна. Лабораторна робота №1
> Lab1: Pavlenko Kateryna

- IT-31/Rishko/README.md
> Lab1: Rishko I.M. IT-31

- IT-31/Shynkler/README.md
> Lab_2 Done

- IT-31/Hrytsyk/README.md
> Lab_2: Грицик Олег ІТ-31

- IT-31/Demidov/README.md
Демідов Денис Сергійович Лаба 1
> Lab1: +Demidov

- IT-31/Domalchuk/README.md
Домальчук Богдан Васильович (ІТ-31) : Лабораторна робота №2
> lab_2: + Domalchuk

- IT-31/Pavlenko/README.md
Lab2: Pavlenko Kateryna IT - 31
> Lab2: Pavlenko Kateryna IT - 31

- IK-31/taras/README.md
> Lab_2: Taras V.I. IK-31

- IT-22/Yunko/README.md
Лабораторна робота 1. ІТ-22. Назар Юнко.
> Лабораторна робота 1. ІТ-22. Назар Юнко.

- IK-31/Bobyk/README.md
> Lab_2:Bobyk

- IT-31/Hrytsyk/README.md
> Lab3: Грицик Олег ІТ-31

- IT-31/Skorinovych/README.md
Lab_1: Андрій Скорінович ІТ-31
> Lab_1: Андрій Скорінович ІТ-31

- IK-31/taras/README.md
> Lab_3: Done

- IK-31/taras/README.md
> Lab_4: Taras IK

- IT-31/Skorinovych/README.md
> Lab_2:Андрій Скорінович ІТ-31

- IT-31/Hrytsyk/README.md
> lab4: Олег Грицик ІТ-31

- IK-31/Vrublevskyi/README.md
> Lab_4: Vrublevskyi V.

- IT-31/Domalchuk/README.md
Домальчук Богдан Васильович ІТ-31
Лабораторна робота №3
> lab_3: + Domalchuk

- IT-31/Skorinovych/README.md
Lab_3 Андрій Скорінович, ІТ-31
> Lab_3 Андрій Скорінович, ІТ-31

- IT-31/pavlyshynets/README.md
> ЛР 5, PAVLYSHYNETS STANISLAV, IT-31

- IT-31/Sotnyk/README.md
> Lab4_IT-31_Vitaliy_Sotnyk

- IK-31/taras/README.md
> Lab_5: Done Taras IK-31

- IK-31/Kohut/README.md
> Lab 1,2 Kohut IK-31

- IK-31/taras/README.md
> Lab_6: Taras IK-31

- IT-31/Domalchuk/README.md
Домальчук Богдан Васильович ІТ-31
Лабораторна робота №5
> lab_5 and lab_6: + Domalchuk

- IK-31/Vrublevskyi/README.md
> Lab_6: Vrublevskyi V., IK-31

- IK-31/hashchenko/README.md
> Lab_5 done by Hashchenko

- IK-31/Kohut/README.md
> Lab_3: Kohut IK-31

- IT-31/Hrytsyk/README.md
> Lab5: Олег Грицик ІТ-31

- IK-31/Kohut/README.md
> Lab 4,5 Kohut IK-31

- IK-31/Lesiuk/README.md
> Lab 1-3: Lesiuk Roman, IK-31

- IK-31/Kohut/README.md
> Lab_6: Done. Kohut IK-31

- IK-31/Lesiuk/README.md
> Lab 4-6, Lesiuk Roman, IK-31

- IK-31/PastukhVova/README.md
Пастух В.А., ІК-31, Labs: 4,5,6
> Lab 4-6, Pastukh, IK-31

- IK-31/hashchenko/README.md
> Lab_6 done by hashchenko

- IT-31/Hrytsyk/README.md
> Lab6: Грицик Олег ІТ-31

- IK-31/Kachor/README.md
> Labs:1,2,3 Kachor Yuriy

- IT-31/Skorinovych/README.md
Lab_5 і Lab_6: Скорінович Андрій ІТ-31
> Lab_5 і Lab_6: Скорінович Андрій ІТ-31

- 2020/IT-23/Pikhovskyi/README.md
Пошта політехніки 
mykhailo.pikhovskyi.itis.2019@lpnu.ua
Довелось створювати папку із роком та групою для виконання лабораторної роботи
> Піховський М.Р Лабораторна 1-2 IT-23

- 2019/IT-23/Добоній Антон/README.md
- 2020/IT-23/Добоній Антон/README.md
> Anton Dobonii

- 2020/IK-31/OnishchenkoYevhenii/README.md
> Оніщенко Є.В. Л.р.№1

- 2020/IT-23/Cherevan Viktoriia/README.md
> Cherevan Viktoriia. IT-23. LAB1

- 2020/IT-31/Кутянська/README.md
Кутянська Юлія, ІТ-31, Лабораторна робота №1
> Кутянська Юлія, ІТ-31, Лабораторна робота №1

- 2020/IT-23/Cherevan Viktoriia/README.md
Cherevan Viktoriia IT-23 Lab2a
> Cherevan Viktoriia IT-23 Lab2a

- 2020/IT-31/Onufrak/README.md
Переробив пул реквест до лаб.1
> Onufrak Andrii IT-31 Lab.1

- 2020/IK-31/Danylo/README.md
lab1:added link
Данило Діана Володимирівна
> Данило Діана Володимирівна lab1

- 2020/IK-31/Bella/README.md
Не мав можливості виконувати лабораторну швидше, тому пропустив дедлайн(
> Белла В.О. Лаб1

- 2020/IT-31/Voloshchuk/README.md
> Олег Волощук ІТ-31 Лаб2а

- 2020/IT-31/Koguch/README.md
1 лабу закину пізніше, якщо так можна
> Когуч Ярослав ІТ-31 ЛАБА2а

- 2020/IK-31/Fedoryshyn/README.md
> Fedorushyn IK-31 Laba1

- 2020/IT-31/Urshanskyi/README.md
Added link to lab2
Added an image and fixed lab1
> Urshanskyi Yurii IT-31 lab2/lab1

- 2020/IT-31/Voloshchuk/README.md
> Волощук О. В. IT-31 лаб2

- 2020/IK-31/Fedoryshyn/README.md
> Laba2a IK-31 Fedoryshyn

- 2020/IT-31/Pavliuk/README.md
https://github.com/dp-pavliuk/labs/tree/master/lab_4
> Павлюк Данило ІТ-31, Lab_4

- 2020/IT-31/Karpa/README.md.txt
https://github.com/Alexkarpa/Alex/tree/master/lab4
> lab4 Karpa IT-31

- 2020/IT-23/Proc/README.md
> lab3 Igor Prots IT-23

- 2020/IT-31/Pavliuk/README.md
https://github.com/dp-pavliuk/labs/tree/master/lab_5
> Павлюк Данило, ІТ-31 Lab 5

- 2020/IK-31/Fedoryshyn/README.md
> Laba4 Fedoryshyn IK-31

- 2020/IK-31/Kokhan/readme.md
https://github.com/alcori/Kokhan-IK-31/tree/main/lab4
> Lab 4 IK-31 Kokhan

- 2020/IK-31/Fedoryshyn/README.md
> IK-31 Fedoryshyn Laba5

- 2021/IK-31/Vitalik_Khomiak/README.md
> Khomiak_IK-31_Lab_1

- 2021/IK-31/Vulchak/README.md
Звіт до лабораторної роботи №1 від студента Вульчак П. Б.
> Вульчак ІК-31 Лабораторна №1

- 2021/IK-31/Nikolaychuk/README.md
> Nikolaychuk_IK-31_Lab1

- 2021/IK-31/Mishakin/README.md
Запахнув обидві лаб. роботи до одного репозиторію, як і було вказано
> Виправлення

- 2021/IK-31/Nikolaychuk/README.md
> Nikolaychuk Lab3 and lab4

- 2021/IK-31/Kuzminskiy/README.md
> Kuzminskiy Lab4

- 2021/IK-31/Hrozovskyi/README.md
Звіт з лабораторної роботи №5 від Грозовського В.О.
> Грозовський ІК-31 Лаб5
